baseURL: https://artikel10.org
languageCode: de
title: Artikel10

menu:
  main:
  - name: Blog
    url: /blog/
  - name: Verein
    url: /verein/

theme:
  - ananke-tweaks
  - ananke

params:
  description: Verein für digitalen Grundrechtsschutz
  background_color_class: bg-dark-gray
  featured_image: images/artikel10-header.jpg
  mastodon: https://chaos.social/@artikel10ev
  twitter: https://twitter.com/artikel10ev

blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
