baseURL: https://artikel10.org
languageCode: de
title: Artikel10 e.V.

menu:
  main:
  - name: Blog
    url: /blog
  - name: Tor Relays
    url: /dienste/tor-relays
  - name: Verein
    url: /verein

theme:
  - ananke-tweaks
  - ananke

params:
  description: Verein für digitalen Grundrechtsschutz
  background_color_class: bg-dark-gray
  featured_image: images/artikel10-header.jpg
  mastodon: https://chaos.social/@artikel10ev
  twitter: https://twitter.com/artikel10ev
  custom_css: [css/ananke-tweaks.css]

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
