baseURL: https://artikel10.org
languageCode: de
title: Artikel10

theme:
  - ananke-tweaks
  - ananke

params:
  background_color_class: bg-dark-gray

blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true

menu:
  main:
  - name: Satzung
    url: /verein/satzung/

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
