#!/bin/bash

if [ ! -d public ]; then
    HUGO_ENV=production hugo
fi

if [ "$1" = "test" ]; then
    rsync -aiv --delete public/ artikel10@artikel10.org: -n
else
    rsync -aiv --delete public/ artikel10@artikel10.org:
fi

PRODUCTION=$(grep -E '<body.*production.*>' public/index.html | wc -l)
if [[ $PRODUCTION = 0 ]]; then
    echo "WARNING: No production build!"
fi
